import React, { useEffect } from "react";

const TermsPage = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-[#fffaf3] min-h-screen py-12 px-6 md:px-20">
      <h1 className="text-4xl font-bold text-[#667D60] mb-8 text-center">
        Terms & Conditions
      </h1>
      <div className="text-gray-900 leading-relaxed space-y-4 max-w-5xl mx-auto text-justify">
        <p>
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>
        <p>
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://swacchh.com/ (‘Website’), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
        </p>
        <p>
          The Platform is owned by Swacchh Products, a company incorporated under the Companies Act, 1956 with its registered office at 22C-14-15, Medhara Street, Powerpet, Eluru, India (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').
        </p>
        <p>
          Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction.
        </p>
        <p>
          ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
        </p>
        <ul className="list-disc ml-8 space-y-2">
          <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration.</li>
          <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered.</li>
          <li>The use of Platform and/or availing of our Services is at your own risk.</li>
          <li>The contents of the Platform and the Services are proprietary to us.</li>
          <li>Unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
          <li>You agree to pay us the charges associated with availing the Services.</li>
          <li>You agree not to use the Platform and/ or Services for any unlawful purpose.</li>
          <li>Website and the Services may contain links to other third party websites.</li>
          <li>Upon initiating a transaction you are entering into a legally binding contract with the Platform Owner.</li>
        </ul>
        <p>
          You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use or Your violation of any law or rights of a third party.
        </p>
        <p>
          All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Eluru, Andhra Pradesh.
        </p>
      </div>
    </div>
  );
};

export default TermsPage;
